# Form implementation generated from reading ui file 'bathroom.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_bathroom(object):
    def setupUi(self, MainWindow_bathroom):
        MainWindow_bathroom.setObjectName("MainWindow_bathroom")
        MainWindow_bathroom.resize(1024, 768)
        MainWindow_bathroom.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135,255), stop:0.427447 rgba(41, 61, 132,235), stop:1 rgba(155,79,165,255));\n"
"border-style: solid;\n"
"border-radius:21px;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_bathroom)
        self.centralwidget.setObjectName("centralwidget")
        self.label_smart_home = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_smart_home.setGeometry(QtCore.QRect(20, 20, 190, 50))
        self.label_smart_home.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_smart_home.setObjectName("label_smart_home")
        self.label_connected_device = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_connected_device.setGeometry(QtCore.QRect(20, 110, 470, 60))
        self.label_connected_device.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_connected_device.setObjectName("label_connected_device")
        self.pushButton_back_to_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_back_to_menu.setGeometry(QtCore.QRect(740, 20, 200, 70))
        self.pushButton_back_to_menu.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_back_to_menu.setObjectName("pushButton_back_to_menu")
        self.label_water_temperature = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_water_temperature.setGeometry(QtCore.QRect(20, 200, 200, 200))
        self.label_water_temperature.setText("")
        self.label_water_temperature.setPixmap(QtGui.QPixmap("icon/water_temparature.jpg"))
        self.label_water_temperature.setScaledContents(True)
        self.label_water_temperature.setObjectName("label_water_temperature")
        self.label_washing_machine = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_washing_machine.setGeometry(QtCore.QRect(260, 200, 200, 200))
        self.label_washing_machine.setText("")
        self.label_washing_machine.setPixmap(QtGui.QPixmap("icon/washing_machine.jpg"))
        self.label_washing_machine.setScaledContents(True)
        self.label_washing_machine.setObjectName("label_washing_machine")
        self.pushButton_off_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off_3.setGeometry(QtCore.QRect(135, 460, 86, 35))
        self.pushButton_off_3.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off_3.setObjectName("pushButton_off_3")
        self.pushButton_on_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on_4.setGeometry(QtCore.QRect(260, 460, 86, 35))
        self.pushButton_on_4.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on_4.setObjectName("pushButton_on_4")
        self.pushButton_on_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on_3.setGeometry(QtCore.QRect(20, 460, 86, 35))
        self.pushButton_on_3.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on_3.setObjectName("pushButton_on_3")
        self.label_name_water_temperature = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_water_temperature.setGeometry(QtCore.QRect(20, 410, 200, 40))
        self.label_name_water_temperature.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_water_temperature.setObjectName("label_name_water_temperature")
        self.label_name_washing_machine = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_washing_machine.setGeometry(QtCore.QRect(260, 410, 200, 40))
        self.label_name_washing_machine.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_washing_machine.setObjectName("label_name_washing_machine")
        self.pushButton_off_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off_4.setGeometry(QtCore.QRect(375, 460, 86, 35))
        self.pushButton_off_4.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off_4.setObjectName("pushButton_off_4")
        MainWindow_bathroom.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_bathroom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_bathroom)

    def retranslateUi(self, MainWindow_bathroom):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_bathroom.setWindowTitle(_translate("MainWindow_bathroom", "MainWindow"))
        self.label_smart_home.setText(_translate("MainWindow_bathroom", "<html><head/><body><p align=\"center\">Санузел</p></body></html>"))
        self.label_connected_device.setText(_translate("MainWindow_bathroom", "<html><head/><body><p align=\"center\">Мои подключенные устройства:</p></body></html>"))
        self.pushButton_back_to_menu.setText(_translate("MainWindow_bathroom", "Назад в меню"))
        self.pushButton_off_3.setText(_translate("MainWindow_bathroom", "Off"))
        self.pushButton_on_4.setText(_translate("MainWindow_bathroom", "On"))
        self.pushButton_on_3.setText(_translate("MainWindow_bathroom", "On"))
        self.label_name_water_temperature.setText(_translate("MainWindow_bathroom", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Температура воды</span></p></body></html>"))
        self.label_name_washing_machine.setText(_translate("MainWindow_bathroom", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Стиральная машина</span></p></body></html>"))
        self.pushButton_off_4.setText(_translate("MainWindow_bathroom", "Off"))
