# Form implementation generated from reading ui file 'garage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_garage(object):
    def setupUi(self, MainWindow_garage):
        MainWindow_garage.setObjectName("MainWindow_garage")
        MainWindow_garage.resize(1024, 768)
        MainWindow_garage.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135,255), stop:0.427447 rgba(41, 61, 132,235), stop:1 rgba(155,79,165,255));\n"
"border-style: solid;\n"
"border-radius:21px;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_garage)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_back_to_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_back_to_menu.setGeometry(QtCore.QRect(740, 20, 200, 70))
        self.pushButton_back_to_menu.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_back_to_menu.setObjectName("pushButton_back_to_menu")
        self.label_connected_device = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_connected_device.setGeometry(QtCore.QRect(20, 110, 470, 60))
        self.label_connected_device.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_connected_device.setObjectName("label_connected_device")
        self.label_smart_home = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_smart_home.setGeometry(QtCore.QRect(20, 20, 190, 50))
        self.label_smart_home.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_smart_home.setObjectName("label_smart_home")
        self.label_garage_door = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_garage_door.setGeometry(QtCore.QRect(20, 200, 200, 200))
        self.label_garage_door.setText("")
        self.label_garage_door.setPixmap(QtGui.QPixmap("icon/garage_door.jpg"))
        self.label_garage_door.setScaledContents(True)
        self.label_garage_door.setObjectName("label_garage_door")
        self.label_column = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_column.setGeometry(QtCore.QRect(260, 200, 200, 200))
        self.label_column.setText("")
        self.label_column.setPixmap(QtGui.QPixmap("icon/column_.jpg"))
        self.label_column.setScaledContents(True)
        self.label_column.setObjectName("label_column")
        self.pushButton_on_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on_4.setGeometry(QtCore.QRect(260, 460, 86, 35))
        self.pushButton_on_4.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on_4.setObjectName("pushButton_on_4")
        self.pushButton_off_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off_3.setGeometry(QtCore.QRect(135, 460, 86, 35))
        self.pushButton_off_3.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off_3.setObjectName("pushButton_off_3")
        self.pushButton_on_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on_3.setGeometry(QtCore.QRect(20, 460, 86, 35))
        self.pushButton_on_3.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on_3.setObjectName("pushButton_on_3")
        self.label_name_column = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_column.setGeometry(QtCore.QRect(260, 410, 200, 40))
        self.label_name_column.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_column.setObjectName("label_name_column")
        self.label_name_garage_door = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_garage_door.setGeometry(QtCore.QRect(20, 410, 200, 40))
        self.label_name_garage_door.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_garage_door.setObjectName("label_name_garage_door")
        self.pushButton_off_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off_4.setGeometry(QtCore.QRect(375, 460, 86, 35))
        self.pushButton_off_4.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off_4.setObjectName("pushButton_off_4")
        MainWindow_garage.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_garage)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_garage)

    def retranslateUi(self, MainWindow_garage):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_garage.setWindowTitle(_translate("MainWindow_garage", "MainWindow"))
        self.pushButton_back_to_menu.setText(_translate("MainWindow_garage", "Назад в меню"))
        self.label_connected_device.setText(_translate("MainWindow_garage", "<html><head/><body><p align=\"center\">Мои подключенные устройства:</p></body></html>"))
        self.label_smart_home.setText(_translate("MainWindow_garage", "<html><head/><body><p align=\"center\">Гараж</p></body></html>"))
        self.pushButton_on_4.setText(_translate("MainWindow_garage", "On"))
        self.pushButton_off_3.setText(_translate("MainWindow_garage", "Off"))
        self.pushButton_on_3.setText(_translate("MainWindow_garage", "On"))
        self.label_name_column.setText(_translate("MainWindow_garage", "<html><head/><body><p align=\"center\">Колонка</p></body></html>"))
        self.label_name_garage_door.setText(_translate("MainWindow_garage", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Гаражная дверь</span></p></body></html>"))
        self.pushButton_off_4.setText(_translate("MainWindow_garage", "Off"))
