# Form implementation generated from reading ui file 'kitchen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Window_Kitchen(object):
    def setupUi(self, Window_Kitchen):
        Window_Kitchen.setObjectName("Window_Kitchen")
        Window_Kitchen.resize(1024, 768)
        Window_Kitchen.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135,255), stop:0.427447 rgba(41, 61, 132,235), stop:1 rgba(155,79,165,255));\n"
"border-style: solid;\n"
"border-radius:21px;")
        self.centralwidget = QtWidgets.QWidget(parent=Window_Kitchen)
        self.centralwidget.setObjectName("centralwidget")
        self.label_smart_home = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_smart_home.setGeometry(QtCore.QRect(20, 20, 190, 50))
        self.label_smart_home.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_smart_home.setObjectName("label_smart_home")
        self.pushButton_back_to_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_back_to_menu.setGeometry(QtCore.QRect(740, 20, 200, 70))
        self.pushButton_back_to_menu.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_back_to_menu.setObjectName("pushButton_back_to_menu")
        self.label_connected_device = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_connected_device.setGeometry(QtCore.QRect(20, 110, 470, 60))
        self.label_connected_device.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_connected_device.setObjectName("label_connected_device")
        self.pushButton_off = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off.setGeometry(QtCore.QRect(135, 460, 85, 35))
        self.pushButton_off.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off.setObjectName("pushButton_off")
        self.pushButton_on = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on.setGeometry(QtCore.QRect(20, 460, 85, 35))
        self.pushButton_on.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on.setObjectName("pushButton_on")
        self.pushButton_off_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off_2.setGeometry(QtCore.QRect(375, 460, 86, 35))
        self.pushButton_off_2.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off_2.setObjectName("pushButton_off_2")
        self.pushButton_on_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on_2.setGeometry(QtCore.QRect(260, 460, 86, 35))
        self.pushButton_on_2.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on_2.setObjectName("pushButton_on_2")
        self.pushButton_off_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off_4.setGeometry(QtCore.QRect(615, 460, 86, 35))
        self.pushButton_off_4.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off_4.setObjectName("pushButton_off_4")
        self.pushButton_on_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on_4.setGeometry(QtCore.QRect(500, 460, 86, 35))
        self.pushButton_on_4.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on_4.setObjectName("pushButton_on_4")
        self.label_power_socket = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_power_socket.setGeometry(QtCore.QRect(20, 200, 200, 200))
        self.label_power_socket.setText("")
        self.label_power_socket.setPixmap(QtGui.QPixmap("icon/light.jpg"))
        self.label_power_socket.setScaledContents(True)
        self.label_power_socket.setObjectName("label_power_socket")
        self.label_the_burner = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_the_burner.setGeometry(QtCore.QRect(260, 200, 200, 200))
        self.label_the_burner.setText("")
        self.label_the_burner.setPixmap(QtGui.QPixmap("icon/konforka.jpeg"))
        self.label_the_burner.setScaledContents(True)
        self.label_the_burner.setWordWrap(False)
        self.label_the_burner.setObjectName("label_the_burner")
        self.label_teapot = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_teapot.setGeometry(QtCore.QRect(500, 200, 200, 200))
        self.label_teapot.setText("")
        self.label_teapot.setPixmap(QtGui.QPixmap("icon/teapot.jpg"))
        self.label_teapot.setScaledContents(True)
        self.label_teapot.setObjectName("label_teapot")
        self.label_name_power_socket = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_power_socket.setGeometry(QtCore.QRect(20, 410, 200, 40))
        self.label_name_power_socket.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_power_socket.setObjectName("label_name_power_socket")
        self.label_name_the_burner = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_the_burner.setGeometry(QtCore.QRect(260, 410, 200, 40))
        self.label_name_the_burner.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_the_burner.setObjectName("label_name_the_burner")
        self.label_name_teapot = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_teapot.setGeometry(QtCore.QRect(500, 410, 200, 40))
        self.label_name_teapot.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_teapot.setObjectName("label_name_teapot")
        Window_Kitchen.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_Kitchen)
        QtCore.QMetaObject.connectSlotsByName(Window_Kitchen)

    def retranslateUi(self, Window_Kitchen):
        _translate = QtCore.QCoreApplication.translate
        Window_Kitchen.setWindowTitle(_translate("Window_Kitchen", "MainWindow"))
        self.label_smart_home.setText(_translate("Window_Kitchen", "<html><head/><body><p align=\"center\">Кухня</p></body></html>"))
        self.pushButton_back_to_menu.setText(_translate("Window_Kitchen", "Назад в меню"))
        self.label_connected_device.setText(_translate("Window_Kitchen", "<html><head/><body><p align=\"center\">Мои подключенные устройства:</p></body></html>"))
        self.pushButton_off.setText(_translate("Window_Kitchen", "Off"))
        self.pushButton_on.setText(_translate("Window_Kitchen", "On"))
        self.pushButton_off_2.setText(_translate("Window_Kitchen", "Off"))
        self.pushButton_on_2.setText(_translate("Window_Kitchen", "On"))
        self.pushButton_off_4.setText(_translate("Window_Kitchen", "Off"))
        self.pushButton_on_4.setText(_translate("Window_Kitchen", "On"))
        self.label_name_power_socket.setText(_translate("Window_Kitchen", "<html><head/><body><p align=\"center\">Розетка</p></body></html>"))
        self.label_name_the_burner.setText(_translate("Window_Kitchen", "<html><head/><body><p align=\"center\">Конфорка</p></body></html>"))
        self.label_name_teapot.setText(_translate("Window_Kitchen", "<html><head/><body><p align=\"center\">Чайник</p></body></html>"))
