# Form implementation generated from reading ui file 'livingroom.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Window_Living_room(object):
    def setupUi(self, Window_Living_room):
        Window_Living_room.setObjectName("Window_Living_room")
        Window_Living_room.resize(1024, 768)
        Window_Living_room.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135,255), stop:0.427447 rgba(41, 61, 132,235), stop:1 rgba(155,79,165,255));\n"
"border-style: solid;\n"
"border-radius:21px;")
        self.centralwidget = QtWidgets.QWidget(parent=Window_Living_room)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_back_to_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_back_to_menu.setGeometry(QtCore.QRect(740, 20, 200, 70))
        self.pushButton_back_to_menu.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_back_to_menu.setObjectName("pushButton_back_to_menu")
        self.label_connected_device = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_connected_device.setGeometry(QtCore.QRect(20, 110, 470, 60))
        self.label_connected_device.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_connected_device.setObjectName("label_connected_device")
        self.label_living_room = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_living_room.setGeometry(QtCore.QRect(20, 20, 190, 50))
        self.label_living_room.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_living_room.setObjectName("label_living_room")
        self.label_conditioner = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_conditioner.setGeometry(QtCore.QRect(20, 200, 200, 200))
        self.label_conditioner.setText("")
        self.label_conditioner.setPixmap(QtGui.QPixmap("icon/conditioner.jpg"))
        self.label_conditioner.setScaledContents(True)
        self.label_conditioner.setObjectName("label_conditioner")
        self.label_tv = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_tv.setGeometry(QtCore.QRect(260, 200, 200, 200))
        self.label_tv.setText("")
        self.label_tv.setPixmap(QtGui.QPixmap("icon/tv.jpg"))
        self.label_tv.setScaledContents(True)
        self.label_tv.setObjectName("label_tv")
        self.label_air_humidifier = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_air_humidifier.setGeometry(QtCore.QRect(500, 200, 200, 200))
        self.label_air_humidifier.setText("")
        self.label_air_humidifier.setPixmap(QtGui.QPixmap("icon/air_humidifier.jpg"))
        self.label_air_humidifier.setScaledContents(True)
        self.label_air_humidifier.setObjectName("label_air_humidifier")
        self.pushButton_off_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off_2.setGeometry(QtCore.QRect(375, 460, 86, 35))
        self.pushButton_off_2.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off_2.setObjectName("pushButton_off_2")
        self.pushButton_off = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off.setGeometry(QtCore.QRect(135, 460, 85, 35))
        self.pushButton_off.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off.setObjectName("pushButton_off")
        self.label_name_air_humidifier = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_air_humidifier.setGeometry(QtCore.QRect(500, 410, 200, 40))
        self.label_name_air_humidifier.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_air_humidifier.setObjectName("label_name_air_humidifier")
        self.label_name_tv = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_tv.setGeometry(QtCore.QRect(260, 410, 200, 40))
        self.label_name_tv.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_tv.setObjectName("label_name_tv")
        self.pushButton_on_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on_4.setGeometry(QtCore.QRect(500, 460, 86, 35))
        self.pushButton_on_4.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on_4.setObjectName("pushButton_on_4")
        self.pushButton_on = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on.setGeometry(QtCore.QRect(20, 460, 85, 35))
        self.pushButton_on.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on.setObjectName("pushButton_on")
        self.label_name_conditioner = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_conditioner.setGeometry(QtCore.QRect(20, 410, 200, 40))
        self.label_name_conditioner.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_name_conditioner.setObjectName("label_name_conditioner")
        self.pushButton_on_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_on_2.setGeometry(QtCore.QRect(260, 460, 86, 35))
        self.pushButton_on_2.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,255,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0,255,0,90);\n"
"}\n"
"")
        self.pushButton_on_2.setObjectName("pushButton_on_2")
        self.pushButton_off_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_off_4.setGeometry(QtCore.QRect(615, 460, 86, 35))
        self.pushButton_off_4.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,0,0,90);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,0,0,90);\n"
"}\n"
"")
        self.pushButton_off_4.setObjectName("pushButton_off_4")
        Window_Living_room.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_Living_room)
        QtCore.QMetaObject.connectSlotsByName(Window_Living_room)

    def retranslateUi(self, Window_Living_room):
        _translate = QtCore.QCoreApplication.translate
        Window_Living_room.setWindowTitle(_translate("Window_Living_room", "MainWindow"))
        self.pushButton_back_to_menu.setText(_translate("Window_Living_room", "Назад в меню"))
        self.label_connected_device.setText(_translate("Window_Living_room", "<html><head/><body><p align=\"center\">Мои подключенные устройства:</p></body></html>"))
        self.label_living_room.setText(_translate("Window_Living_room", "<html><head/><body><p align=\"center\">Гостиная</p></body></html>"))
        self.pushButton_off_2.setText(_translate("Window_Living_room", "Off"))
        self.pushButton_off.setText(_translate("Window_Living_room", "Off"))
        self.label_name_air_humidifier.setText(_translate("Window_Living_room", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Освежитель воздуха</span></p></body></html>"))
        self.label_name_tv.setText(_translate("Window_Living_room", "<html><head/><body><p align=\"center\">Телевизор</p></body></html>"))
        self.pushButton_on_4.setText(_translate("Window_Living_room", "On"))
        self.pushButton_on.setText(_translate("Window_Living_room", "On"))
        self.label_name_conditioner.setText(_translate("Window_Living_room", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Кондиционер</span></p></body></html>"))
        self.pushButton_on_2.setText(_translate("Window_Living_room", "On"))
        self.pushButton_off_4.setText(_translate("Window_Living_room", "Off"))
