# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Window_SmartHome(object):
    def setupUi(self, Window_SmartHome):
        Window_SmartHome.setObjectName("Window_SmartHome")
        Window_SmartHome.resize(1024, 768)
        Window_SmartHome.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135,255), stop:0.427447 rgba(41, 61, 132,235), stop:1 rgba(155,79,165,255));\n"
"border-style: solid;\n"
"border-radius:21px;")
        self.centralwidget = QtWidgets.QWidget(parent=Window_SmartHome)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_kitchen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_kitchen.setGeometry(QtCore.QRect(10, 200, 160, 80))
        self.pushButton_kitchen.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_kitchen.setObjectName("pushButton_kitchen")
        self.pushButton_living_room = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_living_room.setGeometry(QtCore.QRect(10, 300, 160, 80))
        self.pushButton_living_room.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_living_room.setObjectName("pushButton_living_room")
        self.pushButton_garage = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_garage.setGeometry(QtCore.QRect(10, 400, 160, 80))
        self.pushButton_garage.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_garage.setObjectName("pushButton_garage")
        self.pushButton_bedroom = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_bedroom.setGeometry(QtCore.QRect(10, 500, 160, 80))
        self.pushButton_bedroom.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_bedroom.setObjectName("pushButton_bedroom")
        self.pushButton_bathroom = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_bathroom.setGeometry(QtCore.QRect(10, 600, 160, 80))
        self.pushButton_bathroom.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_bathroom.setObjectName("pushButton_bathroom")
        self.label_connected_device = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_connected_device.setGeometry(QtCore.QRect(240, 200, 700, 485))
        self.label_connected_device.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_connected_device.setObjectName("label_connected_device")
        self.label_smart_home = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_smart_home.setGeometry(QtCore.QRect(10, 10, 190, 50))
        self.label_smart_home.setStyleSheet("background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"")
        self.label_smart_home.setObjectName("label_smart_home")
        self.pushButton_exit_programm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit_programm.setGeometry(QtCore.QRect(810, 20, 130, 70))
        self.pushButton_exit_programm.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-raduis: 7px;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size:20pt;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 255, 120, 0.4);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,70);\n"
"}\n"
"")
        self.pushButton_exit_programm.setObjectName("pushButton_exit_programm")
        Window_SmartHome.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_SmartHome)
        QtCore.QMetaObject.connectSlotsByName(Window_SmartHome)

    def retranslateUi(self, Window_SmartHome):
        _translate = QtCore.QCoreApplication.translate
        Window_SmartHome.setWindowTitle(_translate("Window_SmartHome", "Умный дом"))
        self.pushButton_kitchen.setText(_translate("Window_SmartHome", "Кухня"))
        self.pushButton_living_room.setText(_translate("Window_SmartHome", "Гостиная"))
        self.pushButton_garage.setText(_translate("Window_SmartHome", "Гараж"))
        self.pushButton_bedroom.setText(_translate("Window_SmartHome", "Спальня"))
        self.pushButton_bathroom.setText(_translate("Window_SmartHome", "Санузел"))
        self.label_connected_device.setText(_translate("Window_SmartHome", "<html><head/><body><p align=\"center\">Добро пожаловать!<br/>Для управления устройствами,<br/>выберите необходимую <br/>комнату из списка слева.<br/>&lt;---</p></body></html>"))
        self.label_smart_home.setText(_translate("Window_SmartHome", "<html><head/><body><p align=\"center\">Умный дом</p></body></html>"))
        self.pushButton_exit_programm.setText(_translate("Window_SmartHome", "Выход"))



